blog/urls.py
from django.urls import path
from django.http import HttpResponse

from blog import views as views_blog

app_name = 'blog'

urlpatterns = [
    path('', views_blog.blog,name='home'),
    path('post/<int:post_id>', views_blog.post,name='post'),
    path('exemple/', views_blog.exemple,name='exemple')
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home,name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from typing import Any
from django.http import HttpResponse , Http404
from django.shortcuts import render
from blog.data import posts

# Create your views here.
def blog(req):
    context = {
        #'text': 'Estamos no blog',
        'title':'Blog - ',
        'posts': posts,
        }
    return render(req, 'blog/index.html',context)

def post(req:HttpResponse, post_id:Any):
    found_post: dict[str, Any] | None = None
    
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    if found_post is None:
        raise Http404('Post nao encontrado!')
        
    context = {
        #'text': 'Estamos no blog',
        'title':'Blog - ',
        'post': found_post,
        }
    return render(req, 'blog/post.html',context)

def exemple(req):
    context = {
        'text': 'Estamos no exemplo',
        'title':'Exemple - ',
        }
    return render(
        req,
        'blog/exemple.html',
        context,
        )

home/views.py
from django.shortcuts import render

# Create your views here.
def home(req):
    
    context = {
        'text':'Estamos na home',
        'title':'Home - '
               }
    
    return render(
        req,
        'home/index.html',
         context,
        )

blog/templates/blog/exemple.html
{% extends "global/base.html" %}

{% block texto %}{{text}}{% endblock texto %}

blog/templates/blog/index.html
{% extends "global/base.html" %}

{% block texto %}{{text}}{% endblock texto %}

{% block posts %}
    {% for post in posts  %}
        {% include "global/partials/posts.html" %}
    {% endfor %}
   
{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/base.html" %}

{% block texto %}{{text}}{% endblock texto %}

{% block posts %}
    <article class="post single_post">
    <header>
        <h1 class="post__title"></h1>
        <a href="{% url "blog:post" post.id %}">{{post.title}}</a>
    </header>

    <div class="post__body">
        <p>{{post.body}}</p>
    </div>

    </article>
   
{% endblock posts %}

home/templates/home/index.html
{% extends "global/base.html" %}

{% block texto %}{{text}}{% endblock texto %}